### ISSUE TITLE
`bag.itunes.apple.com` necessary for iOS App Store

### ISSUE THREAD

**Issue by puresick** [MoralCode/pihole-antitelemetry#15]
Hey, thank you for these awesome blocklists!

I started using the beta blocklist file and recognized that  `bag.itunes.apple.com` is needed for the iOS app store to be able to load.

**Comment by MoralCode** [comment]
Thanks so much for reporting this! I've moved this domain to the borked list (which at this point should just be treate as a "probably will break something" or "suspected might break something" list). 

Just in case anyone is looking for more info on why this is marked as borked, is there any other info you can provide about what made you believe it was borked (or your process for narrowing it down to this blocklist)? Do you happen to know if this applies to apples other "store" apps on iOS too (like the iTunes store or the one where you can buy apple's physical products - forget what that one is called)

**Comment by puresick** [comment]
Perfect!

I just tested around with the following apps, but they all seem to work correctly while `bag.itunes.apple.com` is being blocked:
- iTunes Store
- Apple Store (the App where you can buy physical Apple products)
- Apple TV
- Apple Music
- Support (Apples Support App)
- Testflight

Only the App Store does not work with `bag.itunes.apple.com` being blocked.
