### ISSUE TITLE
Blocking gstatic.com

### ISSUE THREAD

**Issue by lewis149** [MoralCode/pihole-antitelemetry#4]
While google does track you with this site, it's mostly used ad a CDN, breaking a lot of sites

**Comment by MoralCode** [comment]
Thanks for submitting an issue! 
is this a request to add gstatic to the blocklist or to have it removed?

**Comment by lewis149** [comment]
To have it removed since, while it does track you, it breaks functionality of many sites and apps.

**Comment by MoralCode** [comment]
Which blocklist is causing this problem? I'm not able to find anything containing `gstatic` in any of the three blocklists. Is it possible that another list is blocking the domain?

**Comment by lewis149** [comment]
It's domains.csv, which you'll find [here](https://github.com/MoralCode/pihole-antitelemetry/blob/main/domains.csv)

**Comment by lewis149** [comment]
Is it just a general list of domains google and apple related?

**Comment by MoralCode** [comment]
yeah, i probably should have indicated the function of that file more clearly, the csv file is just a way to track where each domain came from and what it is for in case it is helpful to anyone. the blocklists are the `.txt` files

**Comment by lewis149** [comment]
Oh, okay, thanks!
sorry for being dumb

**Comment by MoralCode** [comment]
no problem! this is on me for not including it in the section of the README that describes what the different files are for
